#
#   Discord Bot Settings
#
#   If you're still unsure, check the wiki for detailed instructions:
#   https://teik.gitbook.io/epicreports/ersdiscord/how-to-start-ers-discord
#


Discord_Settings:
  Discord:
    botToken: "<your-bot-token>"
    serverID: "<your-server-id>"
    channelID: "<your-sever-channel-id>"

Discord_Msg:
  Title: "New Report #%reportID%"
  reported_data:
    Title: "**Reported**"
    Description: "**Name:** `%reportedName%` \n 
                  **UUID:** `%reportedUUID%` \n 
                  **Gamemode:** %reportedGamemode% \n
                  **Health:** %reportedHealth% \n
                  **Server:** %reportedServer% \n
                  **Location:** `%reportedLocation%` \n
                  **IP:** `%reportedIP%` "
  reporter_data:
    Title: "**Reported by**"
    Description: "**Name:** `%reporterName%` \n
                  **UUID:** `%reporterUUID%` \n
                  **Gamemode:** %reporterGamemode% \n
                  **Health:** %reporterHealth% \n
                  **Server:** %reporterServer% \n
                  **Location:** `%reporterLocation%` \n
                  **IP:** `%reporterIP%` "
  reason: "**Report Reason**"
  date: "**Date**"
  status: "**Status**"

Discord_img:
  active: true
  image: "https://imgur.com/oWG8rwW.png"