#
#   Discord Bot Settings
#
#   To send reports to Discord, enter your server ID in the serverID field,
#   and the text channel ID in channelID.
#
#   To get these IDs, enable Developer Mode in Discord, right-click on
#   the server or channel, and select "Copy ID".
#
#   Finally, to get this feature, you need add EpicReports bot to your
#   Discord server. To do this, link here:
#   https://discord.com/oauth2/authorize?client_id=1371538199750643784&permissions=1689384584214592&scope=bot
#
#   If you're still unsure, check the wiki for detailed instructions:
#   [Wiki Link]
#


Discord_Settings:
  Discord:
    botToken: ""
    serverID: ""
    channelID: ""

Discord_Msg:
  Title: "New Report #%reportID%"
  reported_data:
    Title: "**Reported**"
    Description: "**Name:** `%reportedName%` \n 
                  **UUID:** `%reportedUUID%` \n 
                  **Gamemode:** %reportedGamemode% \n
                  **Health:** %reportedHealth% \n
                  **Server:** %reportedServer% \n
                  **Location:** `%reportedLocation%` \n
                  **IP:** `%reportedIP%` "
  reporter_data:
    Title: "**Reported by**"
    Description: "**Name:** `%reporterName%` \n
                  **UUID:** `%reporterUUID%` \n
                  **Gamemode:** %reporterGamemode% \n
                  **Health:** %reporterHealth% \n
                  **Server:** %reporterServer% \n
                  **Location:** `%reporterLocation%` \n
                  **IP:** `%reporterIP%` "
  reason: "**Report Reason**"
  date: "**Date**"
  status: "**Status**"

Discord_img:
  active: true
  image: "https://imgur.com/oWG8rwW.png"